In [2]:
import numpy as np

#### Array 생성

In [2]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[ 1.  4.  5.  8.]


numpy.float64

In [3]:
test_array = np.array(["1", "4", 5, 8], float)  # string 타입으로 입력해도 설정된 float 타입으로 데이터가 저장됨
test_array

array([ 1.,  4.,  5.,  8.])

--------------------------------

#### shape과 reshape

In [4]:
print(test_array.dtype)
print(test_array.shape)

float64
(4,)


In [7]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [10]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
              [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
              [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
              [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [14]:
print(np.array(tensor, int).ndim)
print(np.array(tensor, int).size)
print(np.array(tensor, int).nbytes)

3
48
384


In [19]:
print(np.array(tensor, int).reshape(8, 6).shape)
print(np.array(tensor, int).reshape(-1, 2).shape)
print(np.array(tensor, int).flatten())

(8, 6)
(24, 2)
[1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1 2 5 8 1
 2 5 8 1 2 5 8 1 2 5 8]


--------------------------------

#### index와 slicing

In [22]:
test_array = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
test_array[0][2]

3

In [25]:
test_array[0, 2] = 16
test_array

array([[ 1,  2, 16],
       [ 4,  5,  6]])

In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [27]:
a[1, 1:3]

array([7, 8])

In [28]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

##### 인덱싱을 [::3]이라고 주면 3 row 중 하나씩 가져온다.

--------------------------------

#### arange

In [30]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(0, 5, 0.5) # range와 같은 기능. 세 번째 arg는 step

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [38]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
np.arange(0, 5, 0.1).reshape(5, 10)   # list로 반환받기

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9],
       [ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9],
       [ 3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9],
       [ 4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9]])

--------------------------------

#### ones, zeros, empty

In [41]:
np.zeros(shape  = (10,), dtype = np.float32)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [42]:
np.zeros((2, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [45]:
np.empty(shape = (10, ), dtype = np.float32)  # 비어있는 array를 생성하며, 메모리를 초기화하지 않음

array([  1.00907950e+06,   4.57467897e-41,   1.00907950e+06,
         4.57467897e-41,   6.41952047e-10,   7.98112743e-10,
         8.92618257e-10,   6.36674270e+16,   1.66922064e-07,
         8.92618257e-10], dtype=float32)

In [48]:
print(test_array)
print(np.ones_like(test_array))  # ones_like, empty_like, zeros_like : 입력한 array의 크기대로 0, 1을 채워넣음

[[ 1  2 16]
 [ 4  5  6]]
[[1 1 1]
 [1 1 1]]


--------------------------------

#### eye, identity & diagonal

In [50]:
np.identity(n = 3, dtype = np.float32)  # 단위행렬을 만들어주는 메소드

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [53]:
print(np.eye(N = 3, M = 5, dtype = np.float32))    # 대각행렬을 생성해줌
print(np.eye(N = 3, M = 5, k = 2, dtype = np.float32))    # N과 M은 행렬의 크기, k는 원소가 시작하는 위치

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [58]:
print(np.diag(np.arange(9).reshape(3, 3)))   # 행렬의 대각선 원소만을 추출해줌
print(np.arange(9).reshape(3, 3))
print(np.diag(np.arange(9).reshape(3, 3), k = 1))   # k는 원소가 시작하는 위치

[0 4 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


--------------------------------

#### random sampling

In [59]:
np.random.uniform(0, 1, 10).reshape(2, 5)   # 특정 분포를 따르는 수 를 sampling할 수 있음

array([[ 0.58767086,  0.10252922,  0.97060566,  0.29758175,  0.85436938],
       [ 0.91111409,  0.7672488 ,  0.94096148,  0.79801264,  0.70873113]])

In [60]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 1.35657484,  0.39845082,  0.0957398 , -0.26442105,  1.29472074],
       [-0.69502423, -0.4332103 ,  0.0796188 ,  0.94903997,  1.12914773]])

--------------------------------

#### sum

In [64]:
print(test_array.sum(dtype = np.float32))
print(test_array)

34.0
[[ 1  2 16]
 [ 4  5  6]]


#### axis
 operation function을 실행할 때 기준이 되는 dimension 축을 설정

In [68]:
print(test_array)
print(test_array.sum(dtype = np.float32, axis = 1))
print(test_array.sum(dtype = np.float32, axis = 0))   # 0 : 한 col 기준, 1 : 한 row 기준

[[ 1  2 16]
 [ 4  5  6]]
[ 19.  15.]
[  5.   7.  22.]


#### mean, std

array의 element들의 평균, 표준편차를 구해주는 메소드

In [72]:
print(test_array)
print(test_array.mean())
print(test_array.mean(axis = 1))
print('\n')
print(test_array.std())
print(test_array.std(axis = 1))

[[ 1  2 16]
 [ 4  5  6]]
5.66666666667
[ 6.33333333  5.        ]


4.92160768674
[ 6.84754619  0.81649658]


In [73]:
print(np.sqrt(test_array))
print(np.exp(test_array))

[[ 1.          1.41421356  4.        ]
 [ 2.          2.23606798  2.44948974]]
[[  2.71828183e+00   7.38905610e+00   8.88611052e+06]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02]]


#### concatenate
array를 합치는 함수

In [75]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


In [77]:
print(np.concatenate((a, b), axis = 0))

[1 2 3 2 3 4]


In [82]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 3]])
print(np.concatenate((a, b.T), axis = 1))
print(np.concatenate((a, b), axis = 0))

[[1 2 2]
 [3 4 3]]
[[1 2]
 [3 4]
 [2 3]]
