# Pandas

In [1]:
import pandas as pd

In [2]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep = '\s+', header = None)

In [3]:
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [6]:
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [16]:
df_data['weight_0'] = 1     # weight값 추가
df_data = df_data.drop("MEDV", axis = 1)     # Y값 제거
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [19]:
df_data.shape

(506, 14)

In [20]:
df_matrix = df_data.as_matrix() # 506 x 14
weight_vector = np.random.random_sample((14, 1))   # 14 x 1

In [22]:
weight_vector

array([[ 0.55765907],
       [ 0.5165692 ],
       [ 0.12256141],
       [ 0.88893851],
       [ 0.03502704],
       [ 0.41511912],
       [ 0.93516834],
       [ 0.45909436],
       [ 0.13020126],
       [ 0.64386061],
       [ 0.70440074],
       [ 0.71578883],
       [ 0.96317343],
       [ 0.01061242]])

In [25]:
df_matrix.dot(weight_vector)

array([[ 565.5778861 ],
       [ 541.15240254],
       [ 516.98846919],
       [ 490.63415355],
       [ 502.49870042],
       [ 504.28198354],
       [ 581.56743037],
       [ 616.83478706],
       [ 623.38682954],
       [ 598.26670596],
       [ 613.58024937],
       [ 598.87114126],
       [ 555.16715519],
       [ 568.83325777],
       [ 579.85825221],
       [ 563.01795712],
       [ 529.76330341],
       [ 586.2485287 ],
       [ 470.80348626],
       [ 574.22706036],
       [ 600.28993281],
       [ 596.50518503],
       [ 606.95039552],
       [ 613.92195783],
       [ 604.85899699],
       [ 532.07416874],
       [ 587.41959124],
       [ 538.08325057],
       [ 597.46955456],
       [ 584.62456538],
       [ 586.52378506],
       [ 594.93406902],
       [ 488.94712537],
       [ 582.07186008],
       [ 507.10789032],
       [ 555.81113422],
       [ 537.26336599],
       [ 530.20357693],
       [ 518.52348927],
       [ 527.63170763],
       [ 519.94112363],
       [ 452.645

# Numpy

In [7]:
import numpy as np

In [8]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])

In [14]:
weight_vector.T.dot(x_vector)  # T : transpose, dot : 벡터 곱(결과값은 scalar)

array([[12]])